channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - tdqm
  # --- Cloud & storage ---
  - awscli
  - awswrangler
  - boto3
  - obstore
  # --- Geospatial ---
  - folium
  - gdal
  # --- Array / data ---
  - numpy
  - pandas
  - pyarrow
  # --- Machine learning ---
  # --- Visualization ---
  # --- Jupyter & dev tools ---
  - ipykernel
  - jupyter_contrib_nbextensions
  - jupyter-resource-usage
  - jupyter-ruff
  - jupyterlab-git
  - jupyterlab-myst
  - nb_conda_kernels
  - ruff
  # --- Geophysics ---
  - obspy
  - obsplus
  - pip
  - pip:
    - earthscope-sdk==1.1.0
    - earthscope-cli==1.0.0
    - jupyterlab-jupyterbook_navigation